### PR TITLE
:bug: fix deprecation error on package.json and init.coffee

### PR DESCRIPTION
**Pull request by funsterisdafunniest**
fixing deprecation error with:
   - using activationCommands in package.json
   - using config schema rather than configDefaults in init.coffee

### CODE REVIEW

**Comment by mc10** [comment]
@hd-deman It'd be great if this got merged in, as v1.0.0 will completely remove deprecated features. This PR fixes #18, #19, #20, #23, #25, #26, #27, #28, #30, #31, #33, #34, #35, and #36, so those issues should be closed when this gets merged in.

**Comment by funsterisdafunniest** [comment]
please wait for a few minutes if anyone want to merge this, i'm working on the use dispose rather than unobserve issue

**Comment by funsterisdafunniest** [comment]
done, can be merged if necessary.

**Comment by mc10** [comment]
Updated my previous comment with more issues that this fixes.

**Comment by phh** [comment]
+1

**Comment by kevinsawicki** [comment]
Thanks for this!

**Comment by funsterisdafunniest** [comment]
@kevinsawicki hi, is it alright if i create another pull request? just to beautify the code. i only just realise that we don't need CompositeDisposable just for disposing one config observe.

But, if there's plan to add another config variable to this project then it would be better if we stay with CompositeDisposable since with it, we can contain some observed config within one variable.

**Pull request merged**
